### PR TITLE
[T5A3][T17-B1]Chia Zhe Min

### PR DESCRIPTION
**Pull request by zhems**

### CODE REVIEW

**Comment by pixelducky** [comment]
Good job in playing around with JavaFX.

**Comment by pixelducky** [comment]
@zhems btw are you still having issue with the ImageView?

**Comment by zhems** [comment]
@pixelducky yes. i still can't find an article that addresses my problem

**Comment by pixelducky** [comment]
@zhems weird.. I have cloned your repo and tried to add an image to your fxml via SceneBuilder. The ImageView is rendering fine on my side. Can't reproduce your issue. Try reinstalling Eclipse and JavaFX?
screen shot 2016-09-22 at 2 29 08 am

**Pull request closed without merging**
